### ISSUE TITLE
Reported problem analysing some GTFS feeds where the loaded feeds calendar is NoneType

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#305]
A user has reported that for some GTFS feeds an error is received, suggesting that the calendar has been evaluated as None, and so cannot be evaluated for length (thanks @marcdmallafre ).

The error sent to me is below, and while I don't know the specific context giving rise to this yet (ie. gtfs feed and its configuration), the obvious immediate fix would be to change 

https://github.com/global-healthy-liveable-cities/global-indicators/blob/4c975ad8af136920c185ad80ec3fec2517ce57e2/process/subprocesses/_gtfs_utils.py#L93

to be
```
    if loaded_feeds.calendar is not None and len(loaded_feeds.calendar) != 0:
```

My only concern is, while it should resolve this issue by allowing the code to evaluate this check and perform the `else` action, without knowing the context I can't be sure that it wouldn't be masking some other more fundamental problem that has caused loaded_feeds.calendar to be None rather than an empty dataframe.  Its not necessarily wrong that it is that way, but it would be great to check this out with the source data and configuration before committing a fix that could mask a bigger problem.

The original snippet of error code shared with me is below:

```
Traceback (most recent call last):
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 288, in <module>
    main()
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 284, in main
    gtfs_analysis(codename)
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 121, in gtfs_analysis
    stops_headway = _gtfs_utils.get_hlc_stop_frequency(
  File "/home/ghsci/process/subprocesses/_gtfs_utils.py", line 408, in get_hlc_stop_frequency
    date_service_df = set_date_service_table(loaded_feeds)
  File "/home/ghsci/process/subprocesses/_gtfs_utils.py", line 93, in set_date_service_table
    if len(loaded_feeds.calendar) != 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by carlhiggs** [comment]
Hi @marcdmallafre ,

I've made the change suggested above that should address this issue - but please let me know if there are other issues.  

I can't be sure if its a bigger problem that the `loaded_feeds.calendar` data is `None` without seeing the data and configuration.  It might just be that with the changed approach, for feeds without calendar.txt that presumably must use calendar_dates.txt, it returns None now, rather than an empty dataframe.  So, the new code accepts these as being equivalent conditions and handles them.

So, I'll close this particular issue as it should be solved!
