### ISSUE TITLE
If a GTFS stop id happens to be "NA" (e.g. an abbreviation) it is interpreted as NA or NaN in a numeric sense, causing problems

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#326]
**Describe the bug**
If a GTFS stop id happens to be "NA" (e.g. an abbreviation) it is interpreted as NA or NaN in a numeric sense, causing problems when stop_times are queried on the list of stop ids

**To Reproduce**
Run the GTFS analysis script in the GHSCI workflow using a GTFS feed with 'NA', like that sourced from FGC Ferrocarrils de la Generalitat by @marcdmallafre .  This has a particular stop, 'Terrassa Nacions Unides' that happens to have a stop_id value of "NA" (ie. a two letter string, that ambiguously seems similar to a common way of representing null values).
![image](https://github.com/global-healthy-liveable-cities/global-indicators/assets/12984626/dea15aa4-d375-405c-bf9f-f11d8ad1d354)

The following error arises:
```


/home/ghsci/process/data/transit_feeds/Marc issues/Catalunya/20230613_130317_FGC_Catalunya
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 233, in resolve
    return self.resolvers[key]
  File "/env/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/env/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'nan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 244, in resolve
    return self.temps[key]
KeyError: 'nan'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 291, in <module>
    main()
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 287, in main
    gtfs_analysis(codename)
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 82, in gtfs_analysis
    loaded_feeds.stop_times = loaded_feeds.stop_times.query(
  File "/env/lib/python3.10/site-packages/pandas/core/frame.py", line 4440, in query
    res = self.eval(expr, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/frame.py", line 4566, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/eval.py", line 336, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 809, in __init__
    self.terms = self.parse()
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 828, in parse
    return self._visitor.visit(self.expr)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 719, in visit_Compare
    return self.visit(binop)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 535, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 457, in _maybe_transform_eq_ne
    right = self.visit(node.right, side="right")
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 564, in visit_List
    name = self.env.add_tmp([self.visit(e)(self.env) for e in node.elts])
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 564, in <listcomp>
    name = self.env.add_tmp([self.visit(e)(self.env) for e in node.elts])
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 548, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 86, in __init__
    self._value = self._resolve_name()
  File "/env/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 110, in _resolve_name
    res = self.env.resolve(local_name, is_local=is_local)
  File "/env/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 246, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.errors.UndefinedVariableError: name 'nan' is not defined
```

From the above, it can be seen that the error occurs when querying the stop_times dataframe for stop ids sourced from the filtered stops dataframe:
https://github.com/global-healthy-liveable-cities/global-indicators/blob/8d98e0a16b1ddb9b5b38e112c828265e42cceb19/process/subprocesses/_10_gtfs_analysis.py#L79-L84

When this behaviour is explored interactivley, we see that there is one stop with NaN for a stop id:
```
>>> loaded_feeds.stops.loc[loaded_feeds.stops['stop_id'].isna()]
     stop_lat  stop_lon                stop_name stop_id  wheelchair_boarding
32  41.580134  2.013459  Terrassa Nacions Unides     NaN                    0
```

and I've already given the mystery away above --- its not really NaN, but a two-letter string codename "NA" for an ID.  For some reason, this is misinterpreted when being parsed.  

The issue seems to be discussed in a StackExchange post here: https://stackoverflow.com/questions/33952142/prevent-pandas-from-interpreting-na-as-nan-in-a-string

So, it seems to be an issue of gtfs-lite that we use to parse this GTFS feed; here's its `load_clean_feeds()` function:
https://github.com/wklumpen/gtfs-lite/blob/017b69fa47f8edfdba16c44dc2d0607bb47c59d4/gtfslite/gtfs.py#L155-L163

Possible solutions include:
1. advise users experiencing this error to replace problematic IDs that are interpreted ambiguously as NaN and result in a crash to modify the problematic values 
2. lodge an issue with gtfs-lite (perhaps to allow for optional parameterisation of this behaviour; e.g. by allowing keep_default_na)
3. check for NA stop_ids, and if any present, load that feed again with a custom function either `keep_default_na` values or `na_filter=False` (both approaches reported in above thread and should be experimented with if taking this route)

Perhaps option 2 is best; option 1 is easiest.

**Expected behavior**
Stop IDs with a value of "NA" should not be interpreted as NaN  (its a unique ID so can't be NA)

**Comment by carlhiggs** [comment]
According to the Pandas [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) documentation, the default NaN values are: `[‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘None’, ‘n/a’, ‘nan’, ‘null’]`

So, while no stop_id should be any of those values (being an ID it shouldn't be null), it can be imagined that in some cases there would be possible cases of true null values (e.g. an empty id) or ambiguous strings that could be interpreted that way.

So, hard-coding a way to deal with this is risky --- but having said that, here's a possible approach.

If NaNs are found in the list of stop_ids (shouldn't happen, but might, as it did above, incorrectly), then
- an alert could be issued to the user of the count of NaN id stops
- if there is only one stop with NaN (as in this case) then it can actually be safely interpreted as a string for processing purposes (ie. as `"nan"` instead of `nan`) as it could serve as an identifier
- if there is more than one stop with NaN id then we could alert the user and skip the feed; leave it to them to address the ambiguity

For now, I will code this approach as it seems safer than the alternatives (it doesn't involve manually editing the source data, or ignoring potentially valid NA values; it handles the case of a unique NaN stop, and provides guidance in the case of multiple NaNs).

**Comment by carlhiggs** [comment]
@marcdmallafre , I just implemented the solution proposed above on the enhancements branch, which successfully handles the case of a unique "nan" stop id, as below:
```
/home/ghsci/process/data/transit_feeds/Marc issues/Catalunya/20230613_130317_FGC_Catalunya

Barcelona analysis:
  - /home/ghsci/process/data/transit_feeds/Marc issues/Catalunya/20230613_130317_FGC_Catalunya)
  - 20230601 to 20231231)
  - ['07:00:00', '19:00:00']


     Tram                  0 stops identified (0.05 seconds)
     Metro                24 stops identified (0.28 seconds)
     Rail                 59 stops identified (0.51 seconds)
     Bus                   0 stops identified (0.05 seconds)
     Ferry                 0 stops identified (0.05 seconds)
     Cable tram            0 stops identified (0.04 seconds)
     Aerial lift           0 stops identified (0.05 seconds)
     Funicular             2 stops identified (0.10 seconds)
     Trolleybus            0 stops identified (0.08 seconds)
     Monorail              0 stops identified (0.06 seconds)

Barcelona summary (all feeds):
           tot_stops  headway<=30  headway<=20  pct_headway<=30  pct_headway<=20
mode
Funicular          2            2            2            100.0            100.0
Metro             24           24           24            100.0            100.0
Rail              59           59           59            100.0            100.0
total             85           85           85            100.0            100.0


pt_stops_headway exported to SQL database


Processing completed at 2023-06-29_1224
- Task: create study region boundary
- Duration: 0.04 minutes
```

In the case of multiple nan stop ids, its not clear how to handle this so users will be notified via an alert and the feed in question will be skipped.

**Comment by marcdmallafre** [comment]
@carlhiggs now the  20230613_130317_FGC_Catalunya is working well. Although right now this other GTFS is giving an error when before it identified the stops without any problem. It gives problems with the end date and it is well entered in the config yml file

Could it have something to do with the changes made?

```
/home/ghsci/process/data/transit_feeds/test_gtfs/20230602_070312_RENFE_CERCA
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'end_date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 291, in <module>
    main()
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 287, in main
    gtfs_analysis(codename)
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 78, in gtfs_analysis
    loaded_feeds = gtfslite.GTFS.load_zip(f'{gtfsfeed_path}.zip')
  File "/env/lib/python3.10/site-packages/gtfslite/gtfs.py", line 280, in load_zip
    calendar["end_date"] = pd.to_datetime(calendar["end_date"]).dt.date
  File "/env/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'end_date'
```

**Comment by marcdmallafre** [comment]
Hi @carlhiggs 

Is this issue related to the "NA" value problem? Analyzing another GTFS, this error occurred:

```
home/ghsci/process/data/transit_feeds/test_gtfs/20230329_130123_Metro_Sevilla
Traceback (most recent call last):
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 291, in <module>
    main()
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 287, in main
    gtfs_analysis(codename)
  File "/home/ghsci/process/subprocesses/_10_gtfs_analysis.py", line 78, in gtfs_analysis
    loaded_feeds = gtfslite.GTFS.load_zip(f'{gtfsfeed_path}.zip')
  File "/env/lib/python3.10/site-packages/gtfslite/gtfs.py", line 348, in load_zip
    frequencies = pd.read_csv(
  File "/env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/env/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 812, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 889, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1034, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1192, in pandas._libs.parsers.TextReader._convert_with_dtype
ValueError: Integer column has NA values in column 4
```

**Comment by carlhiggs** [comment]
Hi @marcdmallafre ,

Both the last issues you describe above seem to be different issues --- I think for me to know what's going on, I'll have to see the study region configuration file and the GTFS feed files --- would you be able to send these through to me or share a link?

**Comment by marcdmallafre** [comment]
Hi @carlhiggs,

Here you have: [configuration and transit feed files](https://rovira-my.sharepoint.com/:f:/g/personal/39930171-d_epp_urv_cat/ErRPOh1XipRBjmBSoQnrgvgBCsyzq-v1cQIkfGAnvE1Kqw?e=rFHOJv)

**Comment by carlhiggs** [comment]
Hi @marcdmallafre, See the cross-referenced issues for the details, but the latest release (v4.4.5) should address those issues; let me know how you go!

**Comment by marcdmallafre** [comment]
Hi @carlhiggs,

With the last version, I tried to analyze 8 cities in Spain. Now, there's another issue related to the identified stops.

```
/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_bermibusa_20230216

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_bermibusa_20230216)
  - 20220308 to 20220101)
  - ['07:00:00', '19:00:00']


     Tram                  0 stops identified (0.03 seconds)
     Metro                 0 stops identified (0.02 seconds)
     Rail                  0 stops identified (0.02 seconds)
     Bus                   0 stops identified (0.02 seconds)
     Ferry                 0 stops identified (0.02 seconds)
     Cable tram            0 stops identified (0.02 seconds)
     Aerial lift           0 stops identified (0.02 seconds)
     Funicular             0 stops identified (0.02 seconds)
     Trolleybus            0 stops identified (0.02 seconds)
     Monorail              0 stops identified (0.02 seconds)

/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_bilbobus_20230227

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_bilbobus_20230227)
  - 20220901 to 20220901)
  - ['07:00:00', '19:00:00']


     Tram                  0 stops identified (0.05 seconds)
     Metro                 0 stops identified (0.05 seconds)
     Rail                  0 stops identified (0.05 seconds)
     Bus                   0 stops identified (0.05 seconds)
     Ferry                 0 stops identified (0.05 seconds)
     Cable tram            0 stops identified (0.05 seconds)
     Aerial lift           0 stops identified (0.05 seconds)
     Funicular             0 stops identified (0.05 seconds)
     Trolleybus            0 stops identified (0.04 seconds)
     Monorail              0 stops identified (0.05 seconds)

/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_bizkaibus_20230227

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_bizkaibus_20230227)
  - 20170113 to 20230331)
  - ['07:00:00', '19:00:00']


     Tram               1085 stops identified (24.66 seconds)
     Metro              1085 stops identified (23.74 seconds)
     Rail               1085 stops identified (20.73 seconds)
     Bus                1085 stops identified (20.22 seconds)
     Ferry              1085 stops identified (20.15 seconds)
     Cable tram         1085 stops identified (19.80 seconds)
     Aerial lift        1085 stops identified (20.10 seconds)
     Funicular          1085 stops identified (18.49 seconds)
     Trolleybus         1085 stops identified (18.04 seconds)
     Monorail           1085 stops identified (17.76 seconds)

/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_sopelbus_20230227

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_sopelbus_20230227)
  - 20231101 to 20230815)
  - ['07:00:00', '19:00:00']


     Tram                  0 stops identified (0.05 seconds)
     Metro                 0 stops identified (0.03 seconds)
     Rail                  0 stops identified (0.03 seconds)
     Bus                   0 stops identified (0.03 seconds)
     Ferry                 0 stops identified (0.02 seconds)
     Cable tram            0 stops identified (0.02 seconds)
     Aerial lift           0 stops identified (0.02 seconds)
     Funicular             0 stops identified (0.02 seconds)
     Trolleybus            0 stops identified (0.02 seconds)
     Monorail              0 stops identified (0.02 seconds)

/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_metrobilbao_20230227

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_metrobilbao_20230227)
  - 20220930 to 20221218)
  - ['07:00:00', '19:00:00']


     Tram                 41 stops identified (0.41 seconds)
     Metro                41 stops identified (0.38 seconds)
     Rail                 41 stops identified (0.38 seconds)
     Bus                  41 stops identified (0.38 seconds)
     Ferry                41 stops identified (0.39 seconds)
     Cable tram           41 stops identified (0.38 seconds)
     Aerial lift          41 stops identified (0.38 seconds)
     Funicular            41 stops identified (0.38 seconds)
     Trolleybus           41 stops identified (0.37 seconds)
     Monorail             41 stops identified (0.37 seconds)

/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_euskotren_20230227

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_euskotren_20230227)
  - 20230327 to 20230425)
  - ['07:00:00', '19:00:00']


     Tram                 80 stops identified (0.09 seconds)
     Metro                80 stops identified (0.08 seconds)
     Rail                 80 stops identified (0.08 seconds)
     Bus                  80 stops identified (0.08 seconds)
     Ferry                80 stops identified (0.08 seconds)
     Cable tram           80 stops identified (0.08 seconds)
     Aerial lift          80 stops identified (0.08 seconds)
     Funicular            80 stops identified (0.08 seconds)
     Trolleybus           80 stops identified (0.08 seconds)
     Monorail             80 stops identified (0.08 seconds)

/home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_kbus_20230227

Bilbao analysis:
  - /home/ghsci/process/data/transit_feeds/test_gtfs/gtfs_es_bilbao_kbus_20230227)
  - 20230815 to 20231101)
  - ['07:00:00', '19:00:00']


     Tram                 88 stops identified (0.05 seconds)
     Metro                88 stops identified (0.05 seconds)
     Rail                 88 stops identified (0.05 seconds)
     Bus                  88 stops identified (0.05 seconds)
     Ferry                88 stops identified (0.05 seconds)
     Cable tram           88 stops identified (0.05 seconds)
     Aerial lift          88 stops identified (0.05 seconds)
     Funicular            88 stops identified (0.05 seconds)
     Trolleybus           88 stops identified (0.05 seconds)
     Monorail             88 stops identified (0.05 seconds)

Bilbao summary (all feeds):
             tot_stops  headway<=30  ...  pct_headway<=30  pct_headway<=20
mode                                 ...                                  
Aerial lift       1294          808  ...            62.44            42.12
Bus               1294          808  ...            62.44            42.12
Cable tram        1294          808  ...            62.44            42.12
Ferry             1294          808  ...            62.44            42.12
Funicular         1294          808  ...            62.44            42.12
Metro             1294          808  ...            62.44            42.12
Monorail          1294          808  ...            62.44            42.12
Rail              1294          808  ...            62.44            42.12
Tram              1294          808  ...            62.44            42.12
Trolleybus        1294          808  ...            62.44            42.12
total            12940         8080  ...            62.44            42.12

[11 rows x 5 columns]
```
It seems that it doesn't see the difference from the mode.

Here you have all the  [config, data transit feed, logs and the reports](https://rovira-my.sharepoint.com/:f:/g/personal/39930171-d_epp_urv_cat/EumpthZLsqhEqpRphwkHRyQBpy9moSHPADpxOCLRf8nNBQ?email=carl.higgs%40rmit.edu.au&e=D5ShoV)

**Comment by carlhiggs** [comment]
Thanks @marcdmallafre for picking up on this; should be now resolved on the main branch --- I just made a new release v4.4.6 that addresses it.

What happened was, I added some code to allow people to be more flexible in their configuration of modes

- they could omit 'modes:' (that falls back to default)
- if specifying modes (over-riding default) this could refer to route_type and/or agency_id when doing this ---- but if agency_id isn't used (which it mostly isn't), it doesn't have to be specified (in which case it should default to None)

But the way I implemented it (using the dictionary 'pop' method) was a bit too clever and had an unexpected behaviour (after the first pass, it removed the content of the 'modes' dictionary altogether, instead of the 'route_types' or 'agency_id' key-value pair for a specific mode which was the intent).  This was resolved by making a copy of the mode specific dictionary before popping the key-value pairs to get route_type or agency_id (and replace these with None if they hadn't been specified).

I confirmed the problem by running the analysis for Sevilla using the feeds you shared the other day --- here is the summary before the fix was implemented:
```
Sevilla summary (all feeds):
             tot_stops  headway<=30  headway<=20  pct_headway<=30  pct_headway<=20
mode
Aerial lift         34           34           29           100.00            85.29
Bus                 34           34           29           100.00            85.29
Cable tram          34           34           29           100.00            85.29
Ferry               34           34           29           100.00            85.29
Funicular           34           34           29           100.00            85.29
Metro               34           34           29           100.00            85.29
Monorail            34           34           29           100.00            85.29
Rail                38           34           29            89.47            76.32
Tram                34           34           29           100.00            85.29
Trolleybus          34           34           29           100.00            85.29
total              344          340          290            98.84            84.30
```

Here is the summary after the fix:
```
Sevilla summary (all feeds):
       tot_stops  headway<=30  headway<=20  pct_headway<=30  pct_headway<=20
mode
Metro         21           21           21           100.00           100.00
Rail          17           13            8            76.47            47.06
total         38           34           29            89.47            76.32
```

So, should be all good now

**Comment by marcdmallafre** [comment]
Ok, thanks @carlhiggs 

Now it's running well.
