### ISSUE TITLE
Attempt to generate policy report pdf from GHSCI web app fails

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#446]
**Describe the bug**
There is a bug when attempting to generate the policy summary report from the GHSCI graphical user interface.  This is not the policy indicator report, but a separate summary.  I believe it relates to a change in our PDF templating software, but I'm not yet sure what is causing this.

For a user it doesn't necessarily appear as an obvious bug (other than console output), but rather nothing happens --- and a pdf does not generate.

The console logs the error, which is:
```
Generating policy report (this may take some time)...
list index out of range
Traceback (most recent call last):
  File "/env/lib/python3.12/site-packages/nicegui/events.py", line 413, in handle_event
    result = handler(arguments) if expects_arguments else handler()
                                                          ^^^^^^^^^
  File "/home/ghsci/process/gui.py", line 802, in <lambda>
    ).generate_policy_report(),
      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghsci/process/subprocesses/policy_report.py", line 460, in generate_policy_report
    self.add_page()
  File "/src/fpdf2/fpdf/fpdf.py", line 935, in add_page
    self.header()
  File "/home/ghsci/process/subprocesses/policy_report.py", line 218, in header
    self.write_html(
  File "/src/fpdf2/fpdf/fpdf.py", line 433, in write_html
    html2pdf.feed(text)
  File "/src/fpdf2/fpdf/html.py", line 936, in feed
    super().feed(data)
  File "/env/lib/python3.12/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/env/lib/python3.12/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/html/parser.py", line 414, in parse_endtag
    self.handle_endtag(elem)
  File "/src/fpdf2/fpdf/html.py", line 871, in handle_endtag
    self._end_paragraph()
  File "/src/fpdf2/fpdf/html.py", line 446, in _end_paragraph
    self._column.render()
  File "/src/fpdf2/fpdf/text_region.py", line 615, in render
    self._render_page_lines(text_lines, _first_page_top, page_bottom)
  File "/src/fpdf2/fpdf/text_region.py", line 599, in _render_page_lines
    last_line_height = self._render_column_lines(text_lines, top, bottom)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/fpdf2/fpdf/text_region.py", line 450, in _render_column_lines
    self.pdf._render_styled_text_line(
  File "/src/fpdf2/fpdf/fpdf.py", line 3062, in _render_styled_text_line
    fragments = text_line.get_ordered_fragments()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/fpdf2/fpdf/line_break.py", line 352, in get_ordered_fragments
    directional_runs[-1].append(fragment)
    ~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

This is using v4.5.2 (and v4.5.3) of the software --- so may relate to update of FPDF pdf templating dependency.  Something in the `write_html()` function appears to be causing the error.  I'll aim to look into this later in the week to better understand whether the issue is on our side or in fpdf.

**Comment by carlhiggs** [comment]
There were changes to the fpdf `write_html()` function recently, including to how headings are specified --- those are used heavily in this policy report, so is likely issue relates to this:
https://github.com/py-pdf/fpdf2/releases/tag/2.7.9
> **Deprecated**
> The dd_tag_indent & li_tag_indent parameters of FPDF.write_html() are replaced by the new tag_indents generic parameter.
> The heading_sizes & pre_code_font parameters of FPDF.write_html() are replaced by the new tag_styles generic parameter.

Luckily the policy and spatial indicators reports that use a different template approach aren't impacted.
